### ISSUE TITLE
Multiprocessing + multi tokens

### ISSUE THREAD

**Issue by ret7020** [vP3nguin/GitShodanKey#7]
We can speed up this script, using multiprocessing to parallel search processes. 
We can bypass github limits using multiple api keys from different accounts

**Comment by vP3nguin** [comment]
**We can speed up this script, using multiprocessing to parallel search processes.**
As you have already correctly recognized, this does not work due to the API limits.

**We can bypass github limits using multiple api keys from different accounts**
This would violate the [GitHub Policy](https://docs.github.com/en/site-policy). Since this project is for research purposes only I will not implement this. 
You are free to implement this at your own risk and your own responsibility.
